const fs = require('fs');
let content = fs.readFileSync('src/app/[eventSlug]/tracks/[id]/page.tsx', 'utf-8');

content = content.replace(
  "const { table, preview, reveal } = await searchParams;",
  `const { table, preview, reveal } = await searchParams;
  const event = await prisma.event.findUnique({ where: { slug: resolvedParams.eventSlug } });
  if (!event) return notFound();
  const labelConfig = JSON.parse(event.labelConfig || '{}');
  const featureFlags = JSON.parse(event.featureFlags || '{}');
  const defaultLabels = {
    anonymityPolicy: labelConfig.anonymityPolicy || '本フェスは匿名性を楽しむイベントです。SNS等での制作者の特定や推測に関する投稿は、投票期間終了後までお控えいただけますようお願い申し上げます。',
    lyricsAnalysisAttribution: labelConfig.lyricsAnalysisAttribution || 'Lyrics Analysis generated by Google Gemini AI',
    thumbnailSubmit: labelConfig.thumbnailSubmit || 'この楽曲のサムネイルを投稿する'
  };
  const defaultFeatures = {
    enableThumbnailSubmit: featureFlags.enableThumbnailSubmit ?? true,
    enableAnonymityPolicy: featureFlags.enableAnonymityPolicy ?? true
  };`
);

content = content.replace(
  "return (\n      <Link",
  `if (!defaultFeatures.enableThumbnailSubmit) return null;
    return (
      <Link`
);

content = content.replace(
  "この楽曲のサムネイルを投稿する",
  "{defaultLabels.thumbnailSubmit}"
);

content = content.replace(
  "本フェスは匿名性を楽しむイベントです。SNS等での制作者の特定や推測に関する投稿は、投票期間終了後までお控えいただけますようお願い申し上げます。",
  "{defaultLabels.anonymityPolicy}"
);

content = content.replace(
  "Lyrics Analysis generated by Google Gemini AI",
  "{defaultLabels.lyricsAnalysisAttribution}"
);

// We need to fix the ternary logic!
// From `) : (` to `) : defaultFeatures.enableAnonymityPolicy ? (`
content = content.replace(
  ") : (\n                <div className=\"mt-8 p-5 rounded-2xl bg-yellow-500/5",
  ") : defaultFeatures.enableAnonymityPolicy ? (\n                <div className=\"mt-8 p-5 rounded-2xl bg-yellow-500/5"
);

// From `</div>\n              )}` to `</div>\n              ) : null}`
// Since there's multiple `)}` we have to be precise.
content = content.replace(
  "                </div>\n              )}\n            </div>\n          </div>",
  "                </div>\n              ) : null}\n            </div>\n          </div>"
);

fs.writeFileSync('src/app/[eventSlug]/tracks/[id]/page.tsx', content);
console.log('Tracks detail page dynamically refactored without syntax errors.');
